app:
    resource: '@AppBundle/Controller/'
    type:     annotation

tasks:
    type:     rest
    resource: AppBundle\Controller\TaskController

tags:
    type:     rest
    resource: AppBundle\Controller\TagController

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/'
