AppBundle\Entity\Tag:
    attributes:
        id :
            groups: ['tag']
        priority:
            groups: ['tag', 'task']

AppBundle\Entity\Task:
    attributes:
        id :
            groups: ['task']
        content:
            groups: ['tag', 'task']
        completed:
            groups: ['tag', 'task']
        tag:
            groups: ['task']